// Demo Instagram calendar used by POST /api/content/seed-instagram-calendar (managers only).
export const SAMPLE_CALENDAR_ITEMS = [
  {
    title: 'Behind-the-scenes workflow',
    description: 'Take followers behind the scenes to observe raw production and setup workflow.',
    content_type: 'reel' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-01-30',
    scheduled_time: '18:00',
    status: 'ISSUE' as const,
    caption: 'Ever wonder what goes on before we hit record? Here is our workflow!',
    hashtags: '#behindthescenes #workflow #reels',
    instructions: 'Post to feed and reels with custom cover frame.',
  },
  {
    title: 'Behind-the-scenes workflow',
    description: 'Take followers behind the scenes to observe raw production and setup workflow.',
    content_type: 'reel' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-09-02',
    scheduled_time: '18:00',
    status: 'ISSUE' as const,
    caption: 'Ever wonder what goes on before we hit record? Here is our workflow!',
    hashtags: '#behindthescenes #workflow #reels',
    instructions: 'Post to feed and reels with custom cover frame.',
  },
  {
    title: 'Poll on next template',
    description: 'Interactive story poll asking users which template colorway they want next.',
    content_type: 'story' as const,
    platform: 'instagram' as const,
    category: 'Engagement',
    scheduled_date: '2026-01-01',
    scheduled_time: '14:00',
    status: 'POSTED' as const,
    caption: 'Vote now in our stories!',
    hashtags: '#poll #interactive',
    instructions: 'Add poll sticker: Option A vs Option B.',
  },
  {
    title: 'Poll on next template',
    description: 'Interactive story poll asking users which template colorway they want next.',
    content_type: 'story' as const,
    platform: 'instagram' as const,
    category: 'Engagement',
    scheduled_date: '2026-09-04',
    scheduled_time: '14:00',
    status: 'POSTED' as const,
    caption: 'Vote now in our stories!',
    hashtags: '#poll #interactive',
    instructions: 'Add poll sticker: Option A vs Option B.',
  },
  {
    title: 'Promo reminder',
    description: 'Announcement reminding subscribers of registration cutoff.',
    content_type: 'announcement' as const,
    platform: 'instagram' as const,
    category: 'Promo',
    scheduled_date: '2026-01-03',
    scheduled_time: '19:30',
    status: 'READY_TO_POST' as const,
    caption: 'Last chance for 30% off early bird perks. Link in bio!',
    hashtags: '#promo #limitedoffer',
    instructions: 'Pin to profile highlights and broadcast channel.',
  },
  {
    title: 'Promo reminder',
    description: 'Announcement reminding subscribers of registration cutoff.',
    content_type: 'announcement' as const,
    platform: 'instagram' as const,
    category: 'Promo',
    scheduled_date: '2026-09-08',
    scheduled_time: '19:30',
    status: 'READY_TO_POST' as const,
    caption: 'Last chance for 30% off early bird perks. Link in bio!',
    hashtags: '#promo #limitedoffer',
    instructions: 'Pin to profile highlights and broadcast channel.',
  },
  {
    title: '15s setup hack',
    description: 'Quick educational micro-reel showing smart camera positioning trick.',
    content_type: 'reel' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-01-06',
    scheduled_time: '17:00',
    status: 'EDITING' as const,
    caption: 'Save this 15s hack for your next shoot.',
    hashtags: '#setuphack #tips #production',
    instructions: 'High pacing, sound effects on text pops.',
  },
  {
    title: '15s setup hack',
    description: 'Quick educational micro-reel showing smart camera positioning trick.',
    content_type: 'reel' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-09-10',
    scheduled_time: '17:00',
    status: 'EDITING' as const,
    caption: 'Save this 15s hack for your next shoot.',
    hashtags: '#setuphack #tips #production',
    instructions: 'High pacing, sound effects on text pops.',
  },
  {
    title: 'Creator workflow myth-busting',
    description: 'Deep dive text thread debunking viral equipment myths.',
    content_type: 'thread' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-01-08',
    scheduled_time: '12:00',
    status: 'REVISION' as const,
    caption: 'Stop buying gear you do not need! Read the breakdown 🧵👇',
    hashtags: '#threads #creators #mythbusting',
    instructions: 'Cross-post to Instagram Threads and carousel slides.',
  },
  {
    title: 'Creator workflow myth-busting',
    description: 'Deep dive text thread debunking viral equipment myths.',
    content_type: 'thread' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-09-14',
    scheduled_time: '12:00',
    status: 'REVISION' as const,
    caption: 'Stop buying gear you do not need! Read the breakdown 🧵👇',
    hashtags: '#threads #creators #mythbusting',
    instructions: 'Cross-post to Instagram Threads and carousel slides.',
  },
  {
    title: 'New template drop',
    description: 'Showcase announcement presenting new responsive grid templates.',
    content_type: 'announcement' as const,
    platform: 'instagram' as const,
    category: 'Promo',
    scheduled_date: '2026-01-09',
    scheduled_time: '18:30',
    status: 'READY_TO_POST' as const,
    caption: 'Brand new layouts just dropped inside the template library.',
    hashtags: '#templatedrop #newrelease #design',
    instructions: 'Include swipe-up link sticker in associated story.',
  },
  {
    title: 'New template drop',
    description: 'Showcase announcement presenting new responsive grid templates.',
    content_type: 'announcement' as const,
    platform: 'instagram' as const,
    category: 'Promo',
    scheduled_date: '2026-09-16',
    scheduled_time: '18:30',
    status: 'READY_TO_POST' as const,
    caption: 'Brand new layouts just dropped inside the template library.',
    hashtags: '#templatedrop #newrelease #design',
    instructions: 'Include swipe-up link sticker in associated story.',
  },
  {
    title: 'Checkout link + CTA',
    description: 'Direct response story sequence guiding warm leads to order checkout.',
    content_type: 'story' as const,
    platform: 'instagram' as const,
    category: 'Promo',
    scheduled_date: '2026-01-11',
    scheduled_time: '16:00',
    status: 'POSTED' as const,
    caption: 'Tap the link to lock in bonuses before midnight.',
    hashtags: '#linkinbio #limitedperks',
    instructions: 'Link sticker pointing directly to cart checkout.',
  },
  {
    title: 'Checkout link + CTA',
    description: 'Direct response story sequence guiding warm leads to order checkout.',
    content_type: 'story' as const,
    platform: 'instagram' as const,
    category: 'Promo',
    scheduled_date: '2026-09-19',
    scheduled_time: '16:00',
    status: 'POSTED' as const,
    caption: 'Tap the link to lock in bonuses before midnight.',
    hashtags: '#linkinbio #limitedperks',
    instructions: 'Link sticker pointing directly to cart checkout.',
  },
  {
    title: 'Customer highlights',
    description: 'Multi-slide carousel reviewing real user transformations and quote callouts.',
    content_type: 'carousel' as const,
    platform: 'instagram' as const,
    category: 'Engagement',
    scheduled_date: '2026-01-12',
    scheduled_time: '15:00',
    status: 'EDITING' as const,
    caption: 'See what our community achieved this past month! Swipe through ➡️',
    hashtags: '#communitylove #casestudy #success',
    instructions: 'Slide 1 hook graphic, slide 2-5 user stats, slide 6 comment prompt.',
  },
  {
    title: 'Customer highlights',
    description: 'Multi-slide carousel reviewing real user transformations and quote callouts.',
    content_type: 'carousel' as const,
    platform: 'instagram' as const,
    category: 'Engagement',
    scheduled_date: '2026-09-21',
    scheduled_time: '15:00',
    status: 'EDITING' as const,
    caption: 'See what our community achieved this past month! Swipe through ➡️',
    hashtags: '#communitylove #casestudy #success',
    instructions: 'Slide 1 hook graphic, slide 2-5 user stats, slide 6 comment prompt.',
  },
  {
    title: 'Q&A box',
    description: 'Weekly AMA story box addressing audience content workflow questions.',
    content_type: 'story' as const,
    platform: 'instagram' as const,
    category: 'Engagement',
    scheduled_date: '2026-01-14',
    scheduled_time: '11:00',
    status: 'READY_TO_POST' as const,
    caption: 'Drop your burning video editing questions below!',
    hashtags: '#askmeanything #storyqna',
    instructions: 'Question box sticker with prompt text.',
  },
  {
    title: 'Q&A box',
    description: 'Weekly AMA story box addressing audience content workflow questions.',
    content_type: 'story' as const,
    platform: 'instagram' as const,
    category: 'Engagement',
    scheduled_date: '2026-09-23',
    scheduled_time: '11:00',
    status: 'READY_TO_POST' as const,
    caption: 'Drop your burning video editing questions below!',
    hashtags: '#askmeanything #storyqna',
    instructions: 'Question box sticker with prompt text.',
  },
  {
    title: 'Before-after demo',
    description: 'Color grading and sound design before vs after comparison reel.',
    content_type: 'reel' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-01-20',
    scheduled_time: '18:00',
    status: 'REVISION' as const,
    caption: 'Audio is 50% of your video. Listen with headphones 🎧',
    hashtags: '#colorgrading #sounddesign #cinematic',
    instructions: 'Split screen wipe at second 0:04.',
  },
  {
    title: 'Before-after demo',
    description: 'Color grading and sound design before vs after comparison reel.',
    content_type: 'reel' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-09-25',
    scheduled_time: '18:00',
    status: 'REVISION' as const,
    caption: 'Audio is 50% of your video. Listen with headphones 🎧',
    hashtags: '#colorgrading #sounddesign #cinematic',
    instructions: 'Split screen wipe at second 0:04.',
  },
  {
    title: 'Localization tips',
    description: 'Thread breaking down best practices for caption translations and global reach.',
    content_type: 'thread' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-01-22',
    scheduled_time: '13:00',
    status: 'PLANNED' as const,
    caption: 'Why English-only content limits your potential view count by 60%.',
    hashtags: '#localization #globalreach #threads',
    instructions: 'Draft ready for final manager approval.',
  },
  {
    title: 'Localization tips',
    description: 'Thread breaking down best practices for caption translations and global reach.',
    content_type: 'thread' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-09-27',
    scheduled_time: '13:00',
    status: 'PLANNED' as const,
    caption: 'Why English-only content limits your potential view count by 60%.',
    hashtags: '#localization #globalreach #threads',
    instructions: 'Draft ready for final manager approval.',
  },
  {
    title: 'Feature spotlight',
    description: 'Step-by-step visual carousel explaining the top 3 shortcuts creators overlook.',
    content_type: 'carousel' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-01-24',
    scheduled_time: '17:30',
    status: 'READY_TO_POST' as const,
    caption: 'These 3 keyboard shortcuts will save you 2 hours every week.',
    hashtags: '#productivity #shortcuts #editinghacks',
    instructions: 'High contrast carousel with bold slide numbers.',
  },
  {
    title: 'Feature spotlight',
    description: 'Step-by-step visual carousel explaining the top 3 shortcuts creators overlook.',
    content_type: 'carousel' as const,
    platform: 'instagram' as const,
    category: 'Education',
    scheduled_date: '2026-09-29',
    scheduled_time: '17:30',
    status: 'READY_TO_POST' as const,
    caption: 'These 3 keyboard shortcuts will save you 2 hours every week.',
    hashtags: '#productivity #shortcuts #editinghacks',
    instructions: 'High contrast carousel with bold slide numbers.',
  },
];
